/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/redhat-developer/devconsole-api/pkg/apis/devconsole/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeGitSources implements GitSourceInterface
type FakeGitSources struct {
	Fake *FakeDevconsoleV1alpha1
	ns   string
}

var gitsourcesResource = schema.GroupVersionResource{Group: "devconsole.openshift.io", Version: "v1alpha1", Resource: "gitsources"}

var gitsourcesKind = schema.GroupVersionKind{Group: "devconsole.openshift.io", Version: "v1alpha1", Kind: "GitSource"}

// Get takes name of the gitSource, and returns the corresponding gitSource object, and an error if there is any.
func (c *FakeGitSources) Get(name string, options v1.GetOptions) (result *v1alpha1.GitSource, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(gitsourcesResource, c.ns, name), &v1alpha1.GitSource{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.GitSource), err
}

// List takes label and field selectors, and returns the list of GitSources that match those selectors.
func (c *FakeGitSources) List(opts v1.ListOptions) (result *v1alpha1.GitSourceList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(gitsourcesResource, gitsourcesKind, c.ns, opts), &v1alpha1.GitSourceList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.GitSourceList{ListMeta: obj.(*v1alpha1.GitSourceList).ListMeta}
	for _, item := range obj.(*v1alpha1.GitSourceList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested gitSources.
func (c *FakeGitSources) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(gitsourcesResource, c.ns, opts))

}

// Create takes the representation of a gitSource and creates it.  Returns the server's representation of the gitSource, and an error, if there is any.
func (c *FakeGitSources) Create(gitSource *v1alpha1.GitSource) (result *v1alpha1.GitSource, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(gitsourcesResource, c.ns, gitSource), &v1alpha1.GitSource{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.GitSource), err
}

// Update takes the representation of a gitSource and updates it. Returns the server's representation of the gitSource, and an error, if there is any.
func (c *FakeGitSources) Update(gitSource *v1alpha1.GitSource) (result *v1alpha1.GitSource, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(gitsourcesResource, c.ns, gitSource), &v1alpha1.GitSource{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.GitSource), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeGitSources) UpdateStatus(gitSource *v1alpha1.GitSource) (*v1alpha1.GitSource, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(gitsourcesResource, "status", c.ns, gitSource), &v1alpha1.GitSource{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.GitSource), err
}

// Delete takes name of the gitSource and deletes it. Returns an error if one occurs.
func (c *FakeGitSources) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(gitsourcesResource, c.ns, name), &v1alpha1.GitSource{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeGitSources) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(gitsourcesResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.GitSourceList{})
	return err
}

// Patch applies the patch and returns the patched gitSource.
func (c *FakeGitSources) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.GitSource, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(gitsourcesResource, c.ns, name, pt, data, subresources...), &v1alpha1.GitSource{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.GitSource), err
}
