/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"time"

	v1alpha1 "github.com/redhat-developer/devconsole-api/pkg/apis/devconsole/v1alpha1"
	scheme "github.com/redhat-developer/devconsole-api/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// GitSourceAnalysisesGetter has a method to return a GitSourceAnalysisInterface.
// A group's client should implement this interface.
type GitSourceAnalysisesGetter interface {
	GitSourceAnalysises(namespace string) GitSourceAnalysisInterface
}

// GitSourceAnalysisInterface has methods to work with GitSourceAnalysis resources.
type GitSourceAnalysisInterface interface {
	Create(*v1alpha1.GitSourceAnalysis) (*v1alpha1.GitSourceAnalysis, error)
	Update(*v1alpha1.GitSourceAnalysis) (*v1alpha1.GitSourceAnalysis, error)
	UpdateStatus(*v1alpha1.GitSourceAnalysis) (*v1alpha1.GitSourceAnalysis, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.GitSourceAnalysis, error)
	List(opts v1.ListOptions) (*v1alpha1.GitSourceAnalysisList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.GitSourceAnalysis, err error)
	GitSourceAnalysisExpansion
}

// gitSourceAnalysises implements GitSourceAnalysisInterface
type gitSourceAnalysises struct {
	client rest.Interface
	ns     string
}

// newGitSourceAnalysises returns a GitSourceAnalysises
func newGitSourceAnalysises(c *DevconsoleV1alpha1Client, namespace string) *gitSourceAnalysises {
	return &gitSourceAnalysises{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the gitSourceAnalysis, and returns the corresponding gitSourceAnalysis object, and an error if there is any.
func (c *gitSourceAnalysises) Get(name string, options v1.GetOptions) (result *v1alpha1.GitSourceAnalysis, err error) {
	result = &v1alpha1.GitSourceAnalysis{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("gitsourceanalysises").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of GitSourceAnalysises that match those selectors.
func (c *gitSourceAnalysises) List(opts v1.ListOptions) (result *v1alpha1.GitSourceAnalysisList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.GitSourceAnalysisList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("gitsourceanalysises").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested gitSourceAnalysises.
func (c *gitSourceAnalysises) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("gitsourceanalysises").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a gitSourceAnalysis and creates it.  Returns the server's representation of the gitSourceAnalysis, and an error, if there is any.
func (c *gitSourceAnalysises) Create(gitSourceAnalysis *v1alpha1.GitSourceAnalysis) (result *v1alpha1.GitSourceAnalysis, err error) {
	result = &v1alpha1.GitSourceAnalysis{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("gitsourceanalysises").
		Body(gitSourceAnalysis).
		Do().
		Into(result)
	return
}

// Update takes the representation of a gitSourceAnalysis and updates it. Returns the server's representation of the gitSourceAnalysis, and an error, if there is any.
func (c *gitSourceAnalysises) Update(gitSourceAnalysis *v1alpha1.GitSourceAnalysis) (result *v1alpha1.GitSourceAnalysis, err error) {
	result = &v1alpha1.GitSourceAnalysis{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("gitsourceanalysises").
		Name(gitSourceAnalysis.Name).
		Body(gitSourceAnalysis).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *gitSourceAnalysises) UpdateStatus(gitSourceAnalysis *v1alpha1.GitSourceAnalysis) (result *v1alpha1.GitSourceAnalysis, err error) {
	result = &v1alpha1.GitSourceAnalysis{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("gitsourceanalysises").
		Name(gitSourceAnalysis.Name).
		SubResource("status").
		Body(gitSourceAnalysis).
		Do().
		Into(result)
	return
}

// Delete takes name of the gitSourceAnalysis and deletes it. Returns an error if one occurs.
func (c *gitSourceAnalysises) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("gitsourceanalysises").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *gitSourceAnalysises) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("gitsourceanalysises").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched gitSourceAnalysis.
func (c *gitSourceAnalysises) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.GitSourceAnalysis, err error) {
	result = &v1alpha1.GitSourceAnalysis{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("gitsourceanalysises").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
